apiVersion: topologies.eda.nokia.com/v1
kind: NetworkTopology
metadata:
  name: srl-fabric-example
  namespace: eda
spec:
  operation: Reconcile
  nodeTemplates:
    - name: leaf
      labels:
        eda.nokia.com/role: leaf
        eda.nokia.com/security-profile: managed
      annotations:
        topobuilder.eda.labs/name-prefix: leaf
      nodeProfile: srlinux-ghcr-26.3.1
      platform: 7220 IXR-D3L
    - name: spine
      labels:
        eda.nokia.com/role: spine
        eda.nokia.com/security-profile: managed
      annotations:
        topobuilder.eda.labs/name-prefix: spine
      nodeProfile: srlinux-ghcr-26.3.1
      platform: 7220 IXR-D5
    - name: superspine
      labels:
        eda.nokia.com/role: superspine
        eda.nokia.com/security-profile: managed
      annotations:
        topobuilder.eda.labs/name-prefix: superspine
      nodeProfile: srlinux-ghcr-26.3.1
      platform: 7220 IXR-H5-64D
  nodes:
    - name: superspine1
      template: superspine
      annotations:
        topobuilder.eda.labs/x: "950"
        topobuilder.eda.labs/y: "60"
        topobuilder.eda.labs/breakouts: "1:2"
    - name: spine1
      template: spine
      annotations:
        topobuilder.eda.labs/x: "330"
        topobuilder.eda.labs/y: "430"
        topobuilder.eda.labs/breakouts: "1:4"
    - name: spine2
      template: spine
      annotations:
        topobuilder.eda.labs/x: "1560"
        topobuilder.eda.labs/y: "430"
        topobuilder.eda.labs/breakouts: "1:4"
    - name: leaf1
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "60"
        topobuilder.eda.labs/y: "820"
        topobuilder.eda.labs/breakouts: 3:4x10
    - name: leaf2
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "620"
        topobuilder.eda.labs/y: "820"
    - name: leaf3
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "1180"
        topobuilder.eda.labs/y: "820"
    - name: leaf4
      template: leaf
      annotations:
        topobuilder.eda.labs/x: "1740"
        topobuilder.eda.labs/y: "820"
  linkTemplates:
    - name: isl
      type: InterSwitch
      speed: 25G
      encapType: "Null"
      labels:
        eda.nokia.com/role: InterSwitch
    - name: edge
      type: Edge
      encapType: Dot1q
      labels:
        eda.nokia.com/role: Edge
    - name: isl-r2x400g
      type: InterSwitch
      speed: 25G
      encapType: "Null"
      labels:
        eda.nokia.com/role: InterSwitch
      breakouts:
        - remote:
            channels: 2
            speed: 400G
      annotations:
        topobuilder.eda.labs/breakout-variant: isl
    - name: isl-r4x100g
      type: InterSwitch
      speed: 25G
      encapType: "Null"
      labels:
        eda.nokia.com/role: InterSwitch
      breakouts:
        - remote:
            channels: 4
            speed: 100G
      annotations:
        topobuilder.eda.labs/breakout-variant: isl
    - name: edge-l4x10g
      type: Edge
      encapType: Dot1q
      labels:
        eda.nokia.com/role: Edge
      breakouts:
        - local:
            channels: 4
            speed: 10G
      annotations:
        topobuilder.eda.labs/breakout-variant: edge
  links:
    - name: superspine1-spine1-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-1
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: spine1
            interface: ethernet-1-32
          remote:
            node: superspine1
            interface: ethernet-1-1-1
      template: isl-r2x400g
    - name: superspine1-spine2-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-2
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: spine2
            interface: ethernet-1-32
          remote:
            node: superspine1
            interface: ethernet-1-1-2
      template: isl-r2x400g
    - name: spine1-leaf1-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-3
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-1
          remote:
            node: spine1
            interface: ethernet-1-1-1
      template: isl-r4x100g
    - name: spine1-leaf2-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-4
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf2
            interface: ethernet-1-1
          remote:
            node: spine1
            interface: ethernet-1-1-2
      template: isl-r4x100g
    - name: spine1-leaf3-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-5
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-1
          remote:
            node: spine1
            interface: ethernet-1-1-3
      template: isl-r4x100g
    - name: spine1-leaf4-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-6
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-1
          remote:
            node: spine1
            interface: ethernet-1-1-4
      template: isl-r4x100g
    - name: spine2-leaf1-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-7
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-2
          remote:
            node: spine2
            interface: ethernet-1-1-1
      template: isl-r4x100g
    - name: spine2-leaf2-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-8
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf2
            interface: ethernet-1-2
          remote:
            node: spine2
            interface: ethernet-1-1-2
      template: isl-r4x100g
    - name: spine2-leaf3-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-9
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf3
            interface: ethernet-1-2
          remote:
            node: spine2
            interface: ethernet-1-1-3
      template: isl-r4x100g
    - name: spine2-leaf4-1
      annotations:
        topobuilder.eda.labs/edgeId: edge-10
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-2
          remote:
            node: spine2
            interface: ethernet-1-1-4
      template: isl-r4x100g
    - name: leaf3-leaf4-lag1
      annotations:
        topobuilder.eda.labs/edgeId: edge-11
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-31
          remote:
            node: leaf3
            interface: ethernet-1-31
        - local:
            node: leaf4
            interface: ethernet-1-32
          remote:
            node: leaf3
            interface: ethernet-1-32
      template: isl
    - name: leaf2-tester1
      template: edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-12
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf2
            interface: ethernet-1-10
          sim:
            simNode: tester1
            simNodeInterface: eth1
    - name: leaf4-tools1
      template: edge
      annotations:
        topobuilder.eda.labs/edgeId: edge-13
        topobuilder.eda.labs/memberIndex: "0"
      endpoints:
        - local:
            node: leaf4
            interface: ethernet-1-10
          sim:
            simNode: tools1
            simNodeInterface: eth1
    - name: leaf1-edge-server1
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-3-1
      template: edge-l4x10g
    - name: leaf1-edge-server2
      endpoints:
        - local:
            node: leaf1
            interface: ethernet-1-3-2
      template: edge-l4x10g
  simulation:
    simNodeTemplates:
      - name: testman
        type: TestMan
      - name: multitool
        type: Linux
        image: ghcr.io/srl-labs/network-multitool:latest
    simNodes:
      - name: tester1
        template: testman
        annotations:
          topobuilder.eda.labs/x: "620"
          topobuilder.eda.labs/y: "1150"
      - name: tools1
        template: multitool
        annotations:
          topobuilder.eda.labs/x: "1740"
          topobuilder.eda.labs/y: "1150"
